name: checklist
description: A Simple app to quickly manage checklists.
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 
  uuid:
  rxdart: 
  provider: 
  intl: 
  dio: 
  localstorage: 
  kiwi: 
  flutter_bloc: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 
  build_runner: 
  kiwi_generator: 

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: lib/assets/fonts/OpenSans-Regular.ttf

  assets:
    - lib/assets/configuration.json
